# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dennise Saxton
email: hello@dennisesaxton.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a full stack developer living in Chicago. My current stack
  includes Ruby, Ruby on Rails and AngularJS as well as some Wordpress
  work. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: dennisesaxton
github_username:  tenaciousdee

# Build settings
sass:
  sass_dir: _sass
kramdown:
  input: GFM
